#!/bin/bash
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 10
#SBATCH --mem 31G
#SBATCH --gres=gpu:1
#SBATCH --time 12:00:00                                     # maximum time limit is 12h. We need to rerun the jobs every 12 hours.
#SBATCH --output=./logs/slurm-%j.out

cd $HOME/VI/VLM-R1/                    # change this to where your repo is located
echo $PWD
source ./.env
pixi run bash scripts/evaluate_textbias_69.sh
