#!/bin/bash
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 8
#SBATCH --mem 32G
#SBATCH --gres=gpu:1
#SBATCH --time 12:00:00                                     # maximum time limit is 12h. We need to rerun the jobs every 12 hours.
#SBATCH --output=./logs/slurm-%j.out
#SBATCH --account=ee-452
#SBATCH --qos=ee-452

cd $HOME/VI/VLM-R1/                    # change this to where your repo is located
echo $PWD
source ./.env
pixi run bash scripts/run_sft_lora_text_biased.sh
